frontend/src/Pages/Guide/guides/fctraining/guide.md

Fixed not standard title formatting (My bad)

Fix formatting in FC training guide

---

frontend/src/Pages/Guide/guides/upgrade/guide.md

This should be the final version of the Upgrade guide patch, this changes the original guide to add in additional upgrade guide information and guidance, the changes have been signed off by all 5 council.

upgrade guide with prettier check

---

frontend/src/Pages/Guide/index.js

Restricted skill plans to logged in users (doesn't work otherwise)

Skill plan authentification requirement

---

frontend/src/Pages/Guide/guides/upgrade/guide.md

Adds the rules on hours in fleet required for pilots as discussed in 2021-10-31 meeting.

upgrade_guide_rules

---

frontend/src/Pages/Guide/guides/logi/guide.md

Added in information relating to Nestor training, guide was lacking information on what was required to fly Nestor, got approval from Troy to add in basic information. Amended minor details relating to new meta. Added in Alex's PR changes for Logi again with additional information to help clarify and make it easier to read.

Logi guide patch dec22

---

frontend/src/Pages/Guide/guides/newbro/guide.md

Added in minor meta changes and additonally Alex's logi changes with additonal information to make it more "newbro" friendly.

Newbro patch 22dec

---

frontend/src/Pages/Guide/guides/xup/guide.md

Added info on pilots needing to be within 2 jumps before xing up on WL, added minor info for WL and corrected errors with text/updated information to new meta.

Ffg patch dec21

---

backend/data/skillplan.yaml

This PR is to test whether I can amend the skills plans to make more sense, at the moment they are not that helpful to the newbros who actually need them, they are too vague and force players to train into egold. This should only add one more skill plan to the current list, if it works as intended I will do a full rework of all the plans to make it more comprehensive and useful.

Skill plans revamp stage 1

---

backend/data/skillplan.yaml

Reverts the-ditanian-fleet/waitlist#32

Revert "Skill plans revamp stage 1"

---

backend/data/skillplan.yaml

This PR should fix the line 34 error.

Skill plan test

---

backend/data/skillplan.yaml
backend/data/skills.yaml

Skill plans revamp

---

frontend/src/Pages/Guide/guides/badges/guide.md

adjusted the descriptions on the badges page to help with clarification.

Badges description patch

---

frontend/src/Pages/Guide/guides/newbro/guide.md

Amended the newbro guide requirements section to read more easily. Added hyperlinks to guides for easier access as well.

Newbro Guide Requirements amendment

---

frontend/src/Pages/Guide/guides/logi/guide.md

Added in logi upgrade policy as per FC meeting Jan 2022.

Logi upgrade policy & clarification

---

backend/data/skills.yaml

Not the most elegent solution but covers the problem for now, will revisit this later date to make it "cleaner"

Booster rigging reqs 0

---

backend/data/fitnotes.yaml
backend/src/data/fits.rs
backend/src/routes/fleet.rs
frontend/src/Components/Card.js
frontend/src/Components/FitDisplay.js
frontend/src/Pages/Fits/FittingSortDisplay.js
frontend/src/Pages/Waitlist/displaymodes.js
frontend/src/Pages/Waitlist/index.js

UI imperfections are killing me mentally.

Alt squad numbers & UI tweaks

---

frontend/src/Pages/Guide/guides/badges/guide.md
frontend/src/Pages/Guide/guides/logi/guide.md

Fixed an error for cruiser orbit guidance, km should be m.

Cruiser orbit fix

---

frontend/src/Pages/Guide/guides/bastion/guide.md
frontend/src/Pages/Guide/guides/upgrade/guide.md
frontend/src/Pages/Guide/guides/xup/guide.md

Fixed the broken hyper links for anchoring guide!

Alex patch

---

frontend/src/App/Menu.js
frontend/src/App/Navigation.js
frontend/src/Components/Box.js
frontend/src/Components/Form.js
frontend/src/Components/NoteBox.js
frontend/src/Components/Table.js
frontend/src/Pages/FC/Fleet.js
frontend/src/Pages/Fits/FittingSortDisplay.js
frontend/src/Pages/Fits/ImplantText.js
frontend/src/Pages/Guide/index.js

Hambuger 2.0 // full fleet dscan type totals

---

backend/data/fitnotes.yaml
frontend/src/Components/Copy.js
frontend/src/Components/NoteBox.js
frontend/src/Components/SkillDisplay.js
frontend/src/Pages/Fits/ImplantText.js
frontend/src/Pages/ISKh.js
frontend/src/Pages/Waitlist/XCard.js

+ some other stuff/cleanup
(note boxes being their own universal thing instead of slightly different on each page)
+ click for copy being universal

isk/h url click / tweaked fitcards

---

.vscode/extensions.json
readme.md

Added a readme to help new contributors get going faster. Read me includes:
- Basic contribution guidelines
- Instructions to get the waitlist running within WSL for development purposes
I have included some recommended extensions for people who develop in Visual Studio Code. To add or remove recommended plugins update the array in `.vscode/extensions.json` with plugin IDs. 
_Feedback and/or direct changes from maintainers welcome._

Added Readme

---

frontend/src/Pages/FC/guides/documentation/guide.md
frontend/src/Pages/Guide/guides/upgrade/guide.md

Updates to the logi numbers for FCs, updates to the hour limits for pilots.

FC meeting changes AUG22

---

backend/src/routes/waitlist/invite.rs

Current business rules require an FC to have an L badge. However, they may not have the badge on the waitlist.
This commit allows them to be invited regardless AS LONG AS they are logged into their FC main when they join the waitlist on any character.
--- 
Feature suggested/requested by @TDF-Austar. 
Code verified working with SQLite and MySQL.

Allow FCs to be invited in Nestor without L badge.

---

frontend/src/Pages/Guide/guides/tips/guide.md

Apparently, peterhaneve stopped developing EVEMon, mgoeppner has an actively developed fork.

update evemon link

---

frontend/src/Pages/Pilot/index.js

Can't push to an object.

---

frontend/src/Pages/FC/guides/documentation/guide.md

If the trainee didn't establish the logi cap chain, then who did!?

[fixed] The backseat template to include the most important question.

---

frontend/src/Pages/Waitlist/XCard.js

**FC clicks the button, invite request is pending an ESI response**
**ESI has accepted the invite request** - the invite is sent to the pilot: 
Note: while the invite is sent to the user at this point it can still fail because:
* The pilot is in a fleet (immediate failure)
* The invite times out 
* The pilot triggers a session change
Each of these failures is not reported via ESI so the waitlist state cannot change; however, a small pop error similar to natural phenomena displays on the FCs screen
**ESI has rejected the invite because:** <br/>the user is offline, has a CSPA charge, has blocked the fleet boss or the fleet member limit (fleet cap) has been reached.

Invite status feedback

---

backend/src/routes/fleet.rs

The current behaviour of this endpoint is to terminate when the first error occurs. This typically results in the FC having to press the button multiple times, as trying to kick a pilot who has already left the fleet creates a 404 error. 
This PR does a few things:
1. It removes the `?` operator that returns the ESI error to the UI
2. Evaluates the error to handle so 404 errors can be ignored. All other errors are returned to the UI
3. Counts the number of successful kicks, and then returns a meaningful success message

Improved kick all from fleet

---

frontend/src/Pages/Pilot/Entry.js
frontend/src/Pages/Pilot/PilotHistory.js
frontend/src/Pages/Pilot/index.js

- Removed the "Ban" button
- Added ban history
- Added banned pilot banner
- Added tooltips to profile page filters

Fixed missing profile page commit.

---

frontend/src/Pages/Guide/Badges.js

Removed unused FC ranks

---

readme.md

A bunch of things that caused friction while setting up my dev environment.

Improve development setup documentation

---

frontend/src/Pages/Guide/guides/tips/guide.md

Updated guidance on abyssal damage mods to correct false information.

abyssal guidance fix

---

frontend/src/Components/Badge.js

One final bug fix, farewell TDF.

My final PR
